# -*- coding: utf-8 -*-

scraper_wait_time = 15

# scraped from jetphotos.com
aircraft_types = [
	'Aérospatiale/British Aircraft Corporation Concorde',
	'Airbus A300',
	'Airbus A310',
	'Airbus A318',
	'Airbus A319',
	'Airbus A320',
	'Airbus A321',
	'Airbus A330',
	'Airbus A340',
	'Airbus A350',
	'Airbus A380',
	'Antonov AN-12',
	'Antonov AN-124',
	'Antonov AN-148',
	'Antonov AN-2',
	'Antonov AN-22',
	'Antonov AN-225 Mriya',
	'Antonov AN-24',
	'Antonov AN-26',
	'Antonov AN-32',
	'Antonov AN-72',
	'Antonov AN-74',
	'ATR 42',
	'ATR 72',
	'b738',
	'Beech 1900',
	'Beech 99 Airliner',
	'Boeing 707',
	'Boeing 717',
	'Boeing 720',
	'Boeing 727',
	'Boeing 737',
	'Boeing 747',
	'Boeing 757',
	'Boeing 767',
	'Boeing 777',
	'Boeing 787',
	'Boeing C-17 Globemaster',
	'Boeing KC-135 Stratotanker',
	'Boeing VC-25 (Air Force One)',
	'Bombardier CRJ (Canadair Regional Jet)',
	'Bombardier CSeries CS100',
	'Bombardier CSeries CS300',
	'Bombardier Dash 8',
	'British Aerospace ATP',
	'British Aerospace Avro RJ100',
	'British Aerospace Avro RJ70',
	'British Aerospace Avro RJ85',
	'British Aerospace Avro RJX100',
	'British Aerospace BAC 1-11',
	'British Aerospace BAe-146',
	'British Aerospace Jetstream 31',
	'British Aerospace Jetstream 32',
	'British Aerospace Jetstream 41',
	'Britten-Norman BN-2 Islander',
	'CASA C-212 Aviocar',
	'CASA C-295 Aviocar',
	'CASA CN-235',
	'Convair CV-240',
	'Convair CV-340',
	'Convair CV-440',
	'Convair CV-580',
	'Convair CV-880',
	'Convair CV-990',
	'de Havilland Canada DHC-114 Heron',
	'de Havilland Canada DHC-5 Buffalo',
	'de Havilland Canada DHC-6 Twin Otter',
	'de Havilland Canada DHC-7 (Dash 7)',
	'Dornier Do-228',
	'Dornier Do-328',
	'Douglas DC-2',
	'Douglas DC-3',
	'Douglas DC-4',
	'Douglas DC-6',
	'Douglas DC-7',
	'Douglas DC-8',
	'Embraer 170',
	'Embraer 190',
	'Embraer EMB-110 Bandeirante',
	'Embraer EMB-120 Brasilia',
	'Embraer ERJ Series',
	'Fairchild F-27',
	'Fairchild Metroliner',
	'Fairchild-Hiller FH-227',
	'Fokker 100',
	'Fokker 50',
	'Fokker 70',
	'Fokker F27 Friendship',
	'Fokker F28 Fellowship',
	'Hawker Siddeley HS-125',
	'Hawker Siddeley HS-748',
	'Hawker Siddeley Trident',
	'Ilyushin IL-14',
	'Ilyushin IL-18',
	'Ilyushin IL-62',
	'Ilyushin IL-76',
	'Ilyushin IL-86',
	'Ilyushin IL-96',
	'Let L-410 Turbolet',
	'Lockheed C-130 Hercules',
	'Lockheed C-141 Starlifter',
	'Lockheed C-5 Galaxy',
	'Lockheed L-100 Hercules',
	'Lockheed L-1011',
	'Lockheed L-1049 Super Constellation',
	'Lockheed L-1649 Super Constellation',
	'Lockheed L-188 Electra',
	'Lockheed L-749 Constellation',
	'Lockheed P-3 Orion',
	'McDonnell Douglas DC-10',
	'McDonnell Douglas DC-9',
	'McDonnell Douglas DC-9',
	'McDonnell Douglas KC-10 Extender',
	'McDonnell Douglas MD-11',
	'McDonnell Douglas MD-80',
	'McDonnell Douglas MD-80',
	'McDonnell Douglas MD-90',
	'NAMC YS-11',
	'Piper PA-38',
	'Piper PA-38-112 Tomahawk',
	'Piper PA-38-112 Tomahawk',
	'Saab 2000',
	'Saab 340',
	'Shorts 330',
	'Shorts 360',
	'Sud Aviation SE 210 Caravelle',
	'Sukhoi Superjet 100',
	'Swearingen Metro II',
	'Swearingen Metro III',
	'Tupolev TU-134',
	'Tupolev TU-144 SST',
	'Tupolev TU-154',
	'Tupolev TU-204',
	'Tupolev TU-214',
	'Vickers Vanguard',
	'Vickers VC-10',
	'Vickers Viscount',
	'Yakovlev YAK-40',
	'Yakovlev YAK-42',
	'Fighter &amp; bomber aircraft',
	'Boeing B-52 Stratofortress',
	'Boeing MV-22 Osprey',
	'British Aerospace Harrier',
	'British Aerospace Hawk',
	'English Electric Canberra',
	'Fairchild A-10 Thunderbolt',
	'General Dynamics EF-111 Aardvark',
	'General Dynamics F-111 Aardvark',
	'General Dynamics RF-111 Aardvark',
	'Grumman F-14 Tomcat',
	'Lockheed F-104 Starfighter',
	'Lockheed F-117 Nighthawk',
	'Lockheed Martin F-16 Fighting Falcon',
	'Lockheed Martin F-22 Raptor',
	'McDonnell Douglas F-15 Eagle',
	'McDonnell Douglas F-18 Hornet',
	'McDonnell Douglas F-4 Phantom',
	'Mikoyan-Gurevich Mig-17 Fresco',
	'Mikoyan-Gurevich Mig-21 Lancer',
	'Mikoyan-Gurevich Mig-29 Fulcrum',
	'North American F-100 Super Sabre',
	'North American F-86 Sabre',
	'Northrop B-2A Spirit',
	'Panavia Tornado',
	'Rockwell B-1B Lancer',
	'Saab JAS-39 Gripen',
	'Light aircraft and business jets',
	'Beechcraft 100 King Air',
	'Beechcraft 200 Super King Air',
	'Beechcraft 2000A Starship',
	'Beechcraft 35 Bonanza',
	'Beechcraft 350 Super King Air',
	'Beechcraft 400 Beechjet',
	'Beechcraft 58 Baron',
	'Beechcraft 65 Queen Air',
	'Beechcraft 90 King Air',
	'Cessna 150',
	'Cessna 152',
	'Cessna 172 Skyhawk',
	'Cessna 175 Skylark',
	'Cessna 177 Cardinal',
	'Cessna 180 Skywagon',
	'Cessna 182 Skylane',
	'Cessna 208 Caravan',
	'Cessna 210 Centurion',
	'Cessna 310',
	'Cessna 337 Skymaster',
	'Cessna 402',
	'Cessna 404 Titan',
	'Cessna 414 Chancellor',
	'Cessna 421 Golden Eagle',
	'Cessna 441 Conquest',
	'Cessna 5xx Citation',
	'Cessna 6xx Citation',
	'Cessna 750 Citation X',
	'Cirrus SR20/22',
	'Mooney M-20',
	'Piper J-3 Cub',
	'Piper PA-18 Super Cub',
	'Piper PA-22 Pacer/Tri-Pacer',
	'Piper PA-23 Aztec',
	'Piper PA-24 Comanche',
	'Piper PA-25 Pawnee',
	'Piper PA-28 Cherokee',
	'Piper PA-30 Twin Comanche',
	'Piper PA-31 Navajo',
	'Piper PA-32 Saratoga',
	'Piper PA-34 Seneca',
	'Piper PA-42 Cheyenne',
	'Piper PA-46 Malibu'
]
